runtime: python39  # Menentukan runtime Python 3.9
entrypoint: gunicorn -w 2 -b :$PORT app:app  # Menjalankan aplikasi dengan Gunicorn

# Pengaturan Scaling
instance_class: F2  # Gunakan instance F2 untuk TensorFlow (lebih besar dari default F1)

automatic_scaling:
  target_cpu_utilization: 0.7
  max_instances: 5  # Maksimum 5 instance untuk skalabilitas

# Variabel Lingkungan
env_variables:
  GOOGLE_CLOUD_PROJECT: "medvault-442316"  # Ganti dengan ID proyek Google Cloud Anda
  SECRET_KEY: "your_secret_key"  # Ganti dengan kunci rahasia jika diperlukan

# Handler untuk Static dan Dynamic Content
handlers:
  - url: /static
    static_dir: static  # Arahkan semua file static ke folder `static`

  - url: /.*
    script: auto  # Arahkan semua request lain ke aplikasi Flask
